config/routes.rb
Rails.application.routes.draw do
  resources :bikes
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bike.rb
class Bike < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
    def index
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bikes_helper.rb
module BikesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bikes/index.html.erb
<%# Aqui ponemos un show lindo de bicicletas, o la tabla. No estoy seguro todavia %>
<h1>lol oli llegue</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Enduro</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<html>
<body>
<div class = 'fondo-cool'> 
    <div class = 'col-lg-6'></div>
    <div class = 'col-lg-6 text-center'>
        <div class="plate">
        <p class="script"><span>The Real</span></p>
        <p class="shadow text1">Enduro</p>
        <p class="shadow text2">Bike</p>
        <p class="shadow text3">Data</p>
        <p class="script"><span>By a rider</span></p>
        <br>
        <ul>
            <li><a href=<%= bikes_path %> class="round green">Jump In<span class="round">That is, if you really want to compare bikes</span></a></li>
        </ul> 
        </div>
    </div>
</div>
</body>
</html>